namespace BinarySerializer.Nintendo.N64 {
	public enum RSP_CommandType : byte {
		RSP_GBI1_SpNoop = 0x0,
		RSP_GBI0_Mtx = 0x1,

		RSP_GBI1_MoveMem = 0x3,
		RSP_GBI1_Vtx = 0x4,
		RSP_GBI0_DL = 0x6,
		RSP_GBI1_Sprite2DBase = 0x9,

		RSP_GBI1_LoadUCode = 0xAF,
		RSP_GBI1_BranchZ = 0xB0,
		RSP_GBI1_Tri2 = 0xB1,
		RSP_GBI1_ModifyVtx = 0xB2,
		RSP_GBI1_RDPHalf_2 = 0xB3,
		RSP_GBI1_RDPHalf_1 = 0xB4,
		RSP_GBI1_Line3D = 0xB5,
		RSP_GBI1_ClearGeometryMode = 0xB6,
		RSP_GBI1_SetGeometryMode = 0xB7,
		RSP_GBI1_EndDL = 0xB8,
		RSP_GBI1_SetOtherModeL = 0xB9,
		RSP_GBI1_SetOtherModeH = 0xBA,
		RSP_GBI1_Texture = 0xBB,
		RSP_GBI1_MoveWord = 0xBC,
		RSP_GBI1_PopMtx = 0xBD,
		RSP_GBI1_CullDL = 0xBE,
		RSP_GBI1_Tri1 = 0xBF,
		RSP_GBI1_Noop = 0xC0,
		RSP_S2DEX_SPObjLoadTxtr_Ucode1 = 0xC1,

		RDP_TriFill = 0xC8,
		RDP_TriFillZ = 0xC9,
		RDP_TriTxtr = 0xCA,
		RDP_TriTxtrZ = 0xCB,
		RDP_TriShade = 0xCC,
		RDP_TriShadeZ = 0xCD,
		RDP_TriShadeTxtr = 0xCE,
		RDP_TriShadeTxtrZ = 0xCF,

		DLParser_TexRect = 0xE4,
		DLParser_TexRectFlip = 0xE5,
		DLParser_RDPLoadSync = 0xE6,
		DLParser_RDPPipeSync = 0xE7,
		DLParser_RDPTileSync = 0xE8,
		DLParser_RDPFullSync = 0xE9,
		DLParser_SetKeyGB = 0xEA,
		DLParser_SetKeyR = 0xEB,
		DLParser_SetConvert = 0xEC,
		DLParser_SetScissor = 0xED,
		DLParser_SetPrimDepth = 0xEE,
		DLParser_RDPSetOtherMode = 0xEF,
		DLParser_LoadTLut = 0xF0,

		DLParser_SetTileSize = 0xF2,
		DLParser_LoadBlock = 0xF3,
		DLParser_LoadTile = 0xF4,
		DLParser_SetTile = 0xF5,
		DLParser_FillRect = 0xF6,
		DLParser_SetFillColor = 0xF7,
		DLParser_SetFogColor = 0xF8,
		DLParser_SetBlendColor = 0xF9,
		DLParser_SetPrimColor = 0xFA,
		DLParser_SetEnvColor = 0xFB,
		DLParser_SetCombine = 0xFC,
		DLParser_SetTImg = 0xFD,
		DLParser_SetZImg = 0xFE,
		DLParser_SetCImg = 0xFF
	}
}
