using OpenSpace.EngineObject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;

namespace OpenSpace.AI {
    public static class R3AITypes {

        #region Function Types
        public static List<string> functionTypes = new List<string>(new string[] {
            "evalKeyword",
            "evalCondition",
            "evalOperator",
            "evalFunction",
            "evalProcedure",
            "evalMetaAction",
            "evalBeginMacro",
            "evalBeginMacro",
            "evalEndMacro",
            "evalField",
            "evalDsgVarRef",
            "evalDsgVarRef",
            "evalConstant",
            "evalReal",
            "evalButton",
            "evalConstantVector",
            "evalVector",
            "evalMask",
            "evalModuleRef",
            "evalDsgVarId",
            "evalString",
            "evalLipsSynchroRef",
            "evalFamilyRef",
            "evalPersoRef",
            "evalActionRef",
            "evalSuperObjectRef",
            "evalWayPointRef",
            "evalTextRef",
            "evalComportRef",
            "evalModuleRef",
            "evalSoundEventRef",
            "evalObjectTableRef",
            "evalGameMaterialRef",
            "evalParticleGenerator",
            "evalVisualMaterial",
            "evalColor",
            "eval_42",
            "evalLight",
            "evalCaps",
            "evalSubRoutine",
            "evalNULL"
        });
        #endregion

        #region Keywords
        public static List<string> keywordTable = new List<string>(new string[] {
            "If",
            "If",
            "If",
            "If",
            "If",
            "If",
            "If",
            "If",
            "If",
            "If",
            "If",
            "If",
            "If",
            "If",
            "IfDebug ",
            "IfNotU64 ",
            "Then",
            "Else",
            "EngineGoto",
            "Me",
            "MainActor",
            "Nobody",
            "NoInput",
            "NoSoundEvent",
            "NoSoundEvent",
            "NoSuperObject",
            "Nowhere",
            "NoSOLinksWord ",
            "EmptyText",
            "CapsNull",
            "NoGraph",
            "NoAction",
            "NoGMT",
            "NoVMT",
            "While",
            "BeginWhile",
            "EndWhile",
        });
        #endregion

        #region Operators
        public static List<string> operatorTable = new List<string>(new string[] {
            "Scalar",
            "Scalar",
            "Scalar",
            "Scalar",
            "Scalar",
            "Scalar",
            "Affect",
            "Affect",
            "Affect",
            "Affect",
            "Affect",
            "Affect",
            "Affect",
            "Dot",
            "VectorDot",
            "VectorDot",
            "VectorDot",
            "Vector",
            "Vector",
            "Vector",
            "VectorScalar",
            "VectorScalar",
            "Affect",
            "Affect",
            "Affect",
            "Ultra",
            "ModelCast",
            "Array",
            "Affect"
        });
        #endregion

        #region Functions
        public static List<string> functionTable = new List<string>(new string[] {
            "_fn_p_stGetPersoAbsolutePosition",
            "_fn_p_stGetMyAbsolutePosition",
            "_fn_p_stDistanceFunction",
            "_fn_p_stDistanceToPerso",
            "_fn_p_stDistanceFunction",
            "_fn_p_stDistanceFunction",
            "_fn_p_stDistanceFunction",
            "_fn_p_stDistanceFunction",
            "_fn_p_stDistanceFunction",
            "_fn_p_stDistanceFunction",
            "_fn_p_stDistanceToPersoCenter",
            "_fn_p_stDistanceFunction",
            "_fn_p_stDistanceFunction",
            "_fn_p_stDistanceFunction",
            "_fn_p_stDistanceFunction",
            "_fn_p_stDistanceFunction",
            "_fn_p_stDistanceFunction",
            "_fn_p_stGetRadiusWP",
            "_fn_p_stInterpolationBt3WP",
            "_fn_p_stBezierBt3WP",
            "_fn_p_stDistanceFunction",
            "_fn_p_stGetWpAbsolutePosition",
            "_fn_p_stMathFunctionInt",
            "_fn_p_stMathFunctionInt",
            "_fn_p_stMathFunctionReal",
            "_fn_p_stMathFunctionReal",
            "_fn_p_stMathFunctionReal",
            "_fn_p_stMathFunctionReal",
            "_fn_p_stMathFunctionReal",
            "_fn_p_stMathFunctionReal",
            "_fn_p_stMathFunctionReal",
            "_fn_p_stMathFunctionReal",
            "_fn_p_stMathFunctionReal",
            "_fn_p_stMathFunctionReal",
            "_fn_p_stMathAbsoluteValue",
            "_fn_p_stMathFunctionReal",
            "_fn_p_stMathFunctionReal",
            "_fn_p_stMathFunctionReal",
            "_fn_p_stMathFunctionReal",
            "_fn_p_stMathTernarReal",
            "_fn_p_stMathTernarReal",
            "_fn_p_stMathTernarReal",
            "_fn_p_stMathTernarReal",
            "_fn_p_stMathTernarReal",
            "_fn_p_stMathTernarReal",
            "_fn_p_stRealFunction",
            "_fn_p_stHitPointsAndHitPointsMaxFunction",
            "_fn_p_stHitPointsAndHitPointsMaxFunction",
            "_fn_p_stHitPointsAndHitPointsMaxFunction",
            "_fn_p_stHitPointsAndHitPointsMaxFunction",
            "_fn_p_stHitPointsAndHitPointsMaxFunction",
            "_fn_p_stHitPointsAndHitPointsMaxFunction",
            "_fn_p_stListFunction",
            "_fn_p_stListFunction",
            "_fn_p_stLocalToGlobal",
            "_fn_p_stGlobalToLocal",
            "_fn_p_stLocalToGlobal",
            "_fn_p_stGlobalToLocal",
            "_fn_p_stDummyFunction",
            "_fn_p_stDummyFunction",
            "_fn_p_stDummyFunction",
            "_fn_p_stDummyFunction",
            "_fn_p_st_SPO_GetDrawFlag",
            "_fn_p_GetCollidedSPO",
            "_fn_p_GetCollidedSPO",
            "_fn_p_GetCollidedSPO",
            "_fn_p_stTimeFunction",
            "_fn_p_stTimeFunction",
            "_fn_p_stGetDTFunction",
            "_fn_p_stGetFrameLength",
            "_fn_p_stInputFunction",
            "_fn_p_stInputFunction",
            "_fn_p_stInputFunction",
            "_fn_p_stInputFunction",
            "_fn_p_stInputFunction",
            "_fn_p_stInputFunction",
            "_fn_p_stInputFunction",
            "_fn_p_stCode4VitessePadAnalogique",
            "_fn_p_stMiscFunction",
            "_fn_p_stMiscFunction",
            "_fn_p_stMiscFunction",
            "_fn_p_stMiscFunction",
            "_fn_p_stColorFunction",
            "_fn_p_stColorFunction",
            "_fn_p_stColorFunction",
            "_fn_p_stColorFunction",
            "_fn_p_stColorFunction",
            "_fn_p_stColorFunction",
            "_fn_p_stColorFunction",
            "_fn_p_stColorFunction",
            "_fn_p_stColorFunction",
            "_fn_p_stColorFunction",
            "_fn_p_stColorFunction",
            "_fn_p_stVisualMaterialFunction",
            "_fn_p_stVisualMaterialFunction",
            "_fn_p_stVisualMaterialFunction",
            "_fn_p_stVisualMaterialFunction",
            "_fn_p_stVisualMaterialFunction",
            "_fn_p_stVisualMaterialFunction",
            "_fn_p_stVisualMaterialFunction",
            "_fn_p_stVisualMaterialFunction",
            "_fn_p_stVisualMaterialFunction",
            "_fn_p_st_MultiPlayerFunction",
            "_fn_p_st_MultiPlayerFunction",
            "_fn_p_st_MultiPlayerFunction",
            "_fn_p_st_GetActiveMainActors",
            "_fn_p_st_GetPadInversions",
            "_fn_p_st_GetPadInversions",
            "_fn_p_st_RLIFunction",
            "_fn_p_st_PAD2_Function",
            "_fn_p_st_PAD2_Function",
            "_fn_p_st_PAD2_Function",
            "_fn_p_st_PAD2_Function",
            "_fn_p_st_PAD2_Function",
            "_fn_p_st_PAD2_Function",
            "_fn_p_st_PAD2_Function",
            "_fn_p_stInputFunction",
            "_fn_p_st_TXT_Function",
            "_fn_p_stInputFunction",
            "_fn_p_stInputFunction",
            "_fn_p_stInputFunction",
            "_fn_p_stInputFunction",
            "_fn_p_stInputFunction",
            "_fn_p_stSAV2SaveFunction",
            "_fn_p_stSAV2SaveFunction",
            "_fn_p_stSAV2SaveFunction",
            "_fn_p_stSAV2SaveFunction",
            "_fn_p_stSAV2SaveFunction",
            "_fn_p_stGetTransitionSectorIDFunction",
            "_fn_p_stFFBFunctions",
            "_fn_p_stFFBFunctions",
            "_fn_p_stFFBFunctions",
            "_fn_p_stCreateCheapCharacterList",
            "_fn_p_stTestCheapCharacterList",
            "_fn_p_stGetCheapCharacter",
            "_fn_p_stGetCheapCharacter",
            "_fn_p_stGetCheapCharacter",
            "_fn_p_stCode4PointsDeMagie",
            "_fn_p_stCode4PointsDeMagie",
            "_fn_p_stCode4PointsDeMagie",
            "_fn_p_stCode4PointsDeMagie",
            "_fn_p_stCode4PointsDeMagie",
            "_fn_p_stCode4PointsDeMagie",
            "_fn_p_stCode4PointsDair",
            "_fn_p_stCode4PointsDair",
            "_fn_p_stCode4PointsDair",
            "_fn_p_stCode4PointsDair",
            "_fn_p_stCode4PointsDair",
            "_fn_p_stCode4PointsDair",
            "_fn_p_stCode4PersoLePlusProche",
            "_fn_p_stCode4PersoLePlusProche",
            "_fn_p_stGetNearestActorInCurrentSector",
            "_fn_p_stGetNearestActorInCurrentSector",
            "_fn_p_stCode4PersoLePlusProche",
            "_fn_p_stCode4PersoLePlusProche",
            "_fn_p_stCode4PersoLePlusProche",
            "_fn_p_stCode4PersoLePlusProche",
            "_fn_p_stCode4PersoLePlusProche",
            "_fn_p_stCode4PersoLePlusProche",
            "_fn_p_stCode4PersoLePlusProche",
            "_fn_p_stCode4PersoLePlusProche",
            "_fn_p_stGetNbActivePerso",
            "_fn_p_stCode4PersoLePlusProche",
            "_fn_p_stCode4PersoLePlusProche",
            "_fn_p_stCode4PersoLePlusProche",
            "_fn_p_stCode4PersoLePlusProche",
            "_fn_p_stGetCloserNetwork",
            "_fn_p_stCloserAndCollisionWPInGraph",
            "_fn_p_stCloserWPInGraph",
            "_fn_p_stCloserWPInGraph",
            "_fn_p_stCloserWPInGraph",
            "_fn_p_stCloserWPInGraph",
            "_fn_p_stCloserWPInGraph",
            "_fn_p_stCloserWPInGraph",
            "_fn_p_stCloserWPInGraph",
            "_fn_p_stCloserWPInGraph",
            "_fn_p_stTravelOnAGraph",
            "_fn_p_stTravelOnAGraph",
            "_fn_p_stTravelOnAGraph",
            "_fn_p_stTravelOnAGraph",
            "_fn_p_stTravelOnAGraph",
            "_fn_p_stTravelOnAGraph",
            "_fn_p_stTravelOnAGraph",
            "_fn_p_stGraphToWayFunction",
            "_fn_p_stGraphToWayFunction",
            "_fn_p_stGraphToWayFunction",
            "_fn_p_stGraphToWayFunction",
            "_fn_p_stGraphToWayFunction",
            "_fn_p_stGraphToWayFunction",
            "_fn_p_stGraphToWayFunction",
            "_fn_p_stWayFunction",
            "_fn_p_stWayFunction",
            "_fn_p_stWayFunction",
            "_fn_p_stWayFunction",
            "_fn_p_stWayFunction",
            "_fn_p_stWayFunction",
            "_fn_p_stWayFunction",
            "_fn_p_stWayFunction",
            "_fn_p_stWayFunction",
            "_fn_p_stWayFunction",
            "_fn_p_stWayFunction",
            "_fn_p_stWayFunction",
            "_fn_p_stWayFunction",
            "_fn_p_stGetSituationOnRail",
            "_fn_p_stGraphFunction",
            "_fn_p_stGraphFunction",
            "_fn_p_stGraphFunction",
            "_fn_p_stGraphFunction",
            "_fn_p_stMiscFuncOnTypeOfWP",
            "_fn_p_stPersoCapabilityFunction",
            "_fn_p_stCapabilityFunction",
            "_fn_p_stGetScrollSpeed",
            "_fn_p_stMTGetScrollSpeed",
            "_fn_p_stGetNbFrame",
            "_fn_p_stDotProduct",
            "_fn_p_stVectorOperations",
            "_fn_p_stVectorOperations",
            "_fn_p_stGetSPOCoordinates",
            "_fn_p_stGetSPOCoordinates",
            "_fn_p_stGetSPOCoordinates",
            "_fn_p_stGetSPOCoordinates",
            "_fn_p_stTractionFactorFunction",
            "_fn_p_stGetZDxCenter",
            "_fn_p_stGetZDxCenter",
            "_fn_p_stGetZDxCenter",
            "_fn_p_stGetZDxCenter",
            "_fn_p_stCode4TextAffiche",
            "_fn_p_stCode4TextAffiche",
            "_fn_p_stGetCPUCounter",
            "_fn_p_stFunctTurnToPosition",
            "_fn_p_stFunctPS2",
            "_fn_p_stFunctPS2",
            "_fn_p_stFunctPS2",
            "_fn_p_stSAV2_DoVarsNeedToBeSet",
            "_fn_p_stCINEGetGenerateEvent",
            "_fn_p_stTextComparison",
            "_fn_p_stEmptyText",
            "_fn_p_stCode4VitesseHorizontaleDuPerso",
            "_fn_p_stCode4VitesseHorizontaleDuPerso",
            "_fn_p_st3DFunc",
            "_fn_p_stGetPersoSighting",
            "_fn_p_st3DFunc",
            "_fn_p_st3DFunc",
            "_fn_p_stCode4LitPositionZDx",
            "_fn_p_stCode4LitPositionZDx",
            "_fn_p_stCode4LitPositionZDx",
            "_fn_p_stCode4LitCentreZDx",
            "_fn_p_stCode4LitCentreZDx",
            "_fn_p_stCode4LitCentreZDx",
            "_fn_p_stCode4LitAxeZDx",
            "_fn_p_stCode4LitAxeZDx",
            "_fn_p_stCode4LitAxeZDx",
            "_fn_p_stCode4LitDimensionZDx",
            "_fn_p_stCode4LitDimensionZDx",
            "_fn_p_stCode4LitDimensionZDx",
            "_fn_p_stCode4VecteurPointAxe",
            "_fn_p_stCode4VecteurPointAxe",
            "_fn_p_stVectorFunction",
            "_fn_p_stVectorFunction",
            "_fn_p_stVectorFunction",
            "_fn_p_stVectorFunction",
            "_fn_p_stVectorFunction",
            "_fn_p_stVectorFunction",
            "_fn_p_stVectorAndAngle",
            "_fn_p_stVectorAndAngle",
            "_fn_p_stVectorAndAngle",
            "_fn_p_stGetNormalCollideVector",
            "_fn_p_stGetNormalCollideVector",
            "_fn_p_stGetNormalCollideVector",
            "_fn_p_stGetNormalCollideVector",
            "_fn_p_stGetCollidePoint",
            "_fn_p_stGetCollidePoint",
            "_fn_p_stGetCollidePoint",
            "_fn_p_stGetCollidePoint",
            "_fn_p_stGetCollidePoint",
            "_fn_p_stGetCollidePoint",
            "_fn_p_stGetCollidePoint",
            "_fn_p_stGetCollidePoint",
            "_fn_p_stGetCollidePoint",
            "_fn_p_stGetCollidePoint",
            "_fn_p_stGetCollision",
            "_fn_p_stGetCollision",
            "_fn_p_stGetCollision",
            "_fn_p_stGetCollisionWithCollideMaterial",
            "_fn_p_stGetFirstCollisionInfo",
            "_fn_p_stGameMaterialFunction",
            "_fn_p_stGameMaterialFunction",
            "_fn_p_stGameMaterialFunction",
            "_fn_p_stCollideCommunicationFunc",
            "_fn_p_stCollideCommunicationFunc",
            "_fn_p_stCollideCommunicationFunc",
            "_fn_p_stCollideCommunicationFunc",
            "_fn_p_stGetLastCollisionActor",
            "_fn_p_stComputeRebondVector",
            "_fn_p_st3DFunc",
            "_fn_p_st3DFunc",
            "_fn_p_st3DFunc",
            "_fn_p_st3DFunc",
            "_fn_p_st3DFunc",
            "_fn_p_st3DFunc",
            "_fn_p_stMiscFunction",
            "_fn_p_stNamesFunc",
            "_fn_p_stNamesFunc",
            "_fn_p_stNamesFunc",
            "_fn_p_stNamesFunc",
            "_fn_p_stNamesFunc",
            "_fn_p_stNamesFunc",
            "_fn_p_stNamesFunc",
            "_fn_p_GetMechanicParameter",
            "_fn_p_GetMechanicParameter",
            "_fn_p_GetMechanicParameter",
            "_fn_p_GetMechanicParameter",
            "_fn_p_GetMechanicParameter",
            "_fn_p_GetMechanicParameter",
            "_fn_p_GetMechanicParameter",
            "_fn_p_GetMechanicParameter",
            "_fn_p_GetMechanicParameter",
            "_fn_p_GetMechanicParameter",
            "_fn_p_GetMechanicParameter",
            "_fn_p_GetMechanicParameter",
            "_fn_p_GetMechanicParameter",
            "_fn_p_GetMechanicParameter",
            "_fn_p_GetMechanicParameter",
            "_fn_p_GetMechanicParameter",
            "_fn_p_GetMechanicParameter",
            "_fn_p_ComputeJumpImpulsion",
            "_fn_p_GetMechanicParameter",
            "_fn_p_GetHierarchyLink",
            "_fn_p_GetPriviligedActivationZdx",
            "_fn_p_GetPriviligedActivationZdx",
            "_fn_p_GetPriviligedActivationZdx",
            "_fn_p_GetPriviligedActivationZdx",
            "_fn_p_GetComputationFrequency",
            "_fn_p_GetComputationFrequency",
            "_fn_p_GetComputationFrequency",
            "_fn_p_GetBooleanInArray",
            "_fn_p_GetBooleanInArray",
            "_fn_p_stGetButtonName",
            "_fn_p_GetCustomValuesFunc",
            "_fn_p_GetCustomValuesFunc",
            "_fn_p_GetCustomValuesFunc",
            "_fn_p_stGetDriversAvailable",
            "_fn_p_stGetCurrentLanguageId",
            "_fn_p_stGetNbLanguages",
            "_fn_p_stGetLanguageText",
            "_fn_p_stTextToInt",
            "_fn_p_stGetNbAvailableResolution",
            "_fn_p_stGetCurrentResolution",
            "_fn_p_stSaveCurrentResolution",
            "_fn_p_stIsDisplayModeAvailable",
            "_fn_p_stGetBrightness",
            "_fn_p_stGetNameResolution",
            "_fn_p_stGetVideoOptions",
            "_fn_p_stGetVideoOptions",
            "_fn_p_stGetMSSoundValues",
            "_fn_p_stGetMSSoundValues",
            "_fn_p_stGetStdGameLimit",
            "_fn_p_stGetStdGameLimit",
            "_fn_p_stGetStdGameLimit",
            "_fn_p_stGetCurrentFrame",
            "_fn_p_ExecuteVariable",
            "_fn_p_stComputeProtectKey",
            "_fn_p_stComputeXor",
            "_fn_p_stComputeXor",
            "_fn_p_stComputeXor",
            "_fn_p_stComputeNot",
            "_fn_p_stComputeXor",
            "_fn_p_stComputeXor",
            "_fn_p_stComputeXor",
            "_fn_p_stComputeXor",
            "_fn_p_stComputeXor",
            "_fn_p_stGetXBoxRegion",
            "_fn_p_stCreditsManagementFunctions",
            "_fn_p_stCreditsManagementFunctions",
            "_fn_p_stCreditsManagementFunctions",
            "_CAM_fn_p_stGetVectorParameter",
            "_CAM_fn_p_stGetVectorParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetRealParameter",
            "_CAM_fn_p_stGetTargetedSuperObject",
            "_CAM_fn_p_stGetTypeOfViewport",
            "_CAM_fn_p_stGetCameraOfViewport",
            "_CAM_fn_p_stGetCameraOfViewport",
            "_CAM_fn_p_stComputeTargetWithTgtPerso",
            "_CAM_fn_p_stComputeCurrentTarget",
            "_CAM_fn_p_stGetSectorCameraType",
            "_CAM_fn_p_stGetBestPos",
            "_CAM_fn_p_stGetSetTransparencyFlag",
            "_CAM_fn_p_stGetSetMirrorFlag",
            "_CAM_fn_p_stGetSetMirrorFlag",
            "_CAM_fn_p_GetViewportCoordinates",
            "_fn_p_BackMode",
            "_fn_p_MarioMode",
            "_fn_p_StrafeLockMode",
            "_fn_p_GetViewFinderDistance",
            "_LNK_fn_p_Init",
            "_LNK_fn_p_DoBehaviour",
            "_LNK_fn_p_Kill",
            "_LNK_fn_p_GetNoCutPoints",
            "_LNK_fn_p_GetCutPoint",
            "_LNK_fn_p_FollowLinkDirection",
            "_fn_p_stOptionGetHandle",
            "_fn_p_stOptionGetHandleState",
            "_fn_p_stOptionGetHandleState",
            "_fn_p_stOptionGetHandleState",
            "_fn_p_stOptionGetHandleState",
            "_fn_p_stOptionGetHandleState",
            "_fn_p_stOptionGetTypeVolume",
            "_fn_p_stOptionGetTypeVolume",
            "_fn_p_stOptionGetTypeVolume",
            "_fn_p_stOptionGetTypeVolume",
            "_fn_p_stOptionGetTypeVolume",
            "_fn_p_stIsSoundPlaying",
            "_fn_p_stMusicMarkerSlotControlFunction",
            "_fn_p_stMonitoringSetVariable",
            "_fn_p_stR3GetValue",
            "_fn_p_stR3GetValue",
            "_fn_p_stFunctPS2",
            "_fn_p_stScreenFunctions",
            "_fn_p_stMCFunc",
            "_fn_p_st_SinusEffect_GetPosition",
            "_fn_p_st_SFX_GetLightReflectionStatus",
            "_fn_p_st_SFX_GetWaterCirclesStatus",
            "_fn_p_st_SFX_IsLightReflectionPossible",
            "_fn_p_st_SFX_IsWaterCirclesPossible",
            "_fn_p_st_AGO_GetHandle",
            "_fn_p_stIsMcValid",
            "_fn_p_st_FormatMC"
        });
        #endregion

        #region Procedures
        public static List<string> procedureTable = new List<string>(new string[] {
            "_fn_p_stHitPointsProcedure",
            "_fn_p_stHitPointsProcedure",
            "_fn_p_stHitPointsProcedure",
            "_fn_p_stHitPointsProcedure",
            "_fn_p_stHitPointsProcedure",
            "_fn_p_stHitPointsProcedure",
            "_fn_p_stHitPointsMaxProcedure",
            "_fn_p_stHitPointsMaxProcedure",
            "_fn_p_stHitPointsMaxProcedure",
            "_fn_p_stHitPointsMaxProcedure",
            "_fn_p_stHitPointsMaxProcedure",
            "_fn_p_stTransparenceProcedure",
            "_fn_p_stTransparenceProcedure",
            "_fn_p_st_ACT_SetDrawFlag",
            "_fn_p_stSkinMaterialProcedure",
            "_fn_p_stSkinMaterialProcedure",
            "_fn_p_stTransparenceProcedure",
            "_fn_p_stTransparenceProcedure",
            "_fn_p_stTransparenceProcedure",
            "_fn_p_stTransparenceProcedure",
            "_fn_p_stListZDDZDEProcedure",
            "_fn_p_stListZDDZDEProcedure",
            "_fn_p_stListZDDZDEProcedure",
            "_fn_p_stListZDDZDEProcedure",
            "_fn_p_stListZDDZDEProcedure",
            "_fn_p_stListZDDZDEProcedure",
            "_fn_p_stListZDDZDEProcedure",
            "_fn_p_stListProcedure",
            "_fn_p_stListProcedure",
            "_fn_p_stListProcedure",
            "_fn_p_stListProcedure",
            "_fn_p_stListProcedure",
            "_fn_p_stListProcedure",
            "_fn_p_stListProcedure",
            "_fn_p_stListProcedure",
            "_fn_p_stListProcedure",
            "_fn_p_stListProcedure",
            "_fn_p_stListProcedure",
            "_fn_p_stListProcedure",
            "_fn_p_stListProcedure",
            "_fn_p_stListEnsembleProcedure",
            "_fn_p_stListEnsembleProcedure",
            "_fn_p_stListEnsembleProcedure",
            "_fn_p_stListEnsembleProcedure",
            "_fn_p_stFogProcedure",
            "_fn_p_stFogProcedure",
            "_fn_p_stFogProcedure",
            "_fn_p_stFogProcedure",
            "_fn_p_stFogProcedure",
            "_fn_p_stFogProcedure",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_st_SinusEffect_SetFreq",
            "_fn_p_st_SinusEffect_SetAmplitude",
            "_fn_p_st_SinusEffect_SetState",
            "_fn_p_st_SinusEffect_SetFreq",
            "_fn_p_st_SinusEffect_SetFreq",
            "_fn_p_st_SinusEffect_SetFreq",
            "_fn_p_st_SinusEffect_SetRLIParams",
            "_fn_p_st_SinusEffect_SetRLIParams",
            "_fn_p_st_SPO_SetDrawFlag",
            "_fn_p_st_SPO_SetEngineDisplayModeFlag",
            "_fn_p_stKeyboardProcedure",
            "_fn_p_stKeyboardProcedure",
            "_fn_p_stNoneProcedure",
            "_fn_p_stTraceProcedure",
            "_fn_p_stChangeComportIntelligenceProcedure",
            "_fn_p_stChangeComportReflexProcedure",
            "_fn_p_stChangeMyComportIntelligenceProcedure",
            "_fn_p_stChangeMyComportReflexProcedure",
            "_fn_p_stChangeMyComportIntelligenceAndReflexProcedure",
            "_fn_p_stChangeActionProcedure",
            "_fn_p_stChangeActionProcedure",
            "_fn_p_stChangeActionRandomProcedure",
            "_fn_p_stChangeActionProcedure",
            "_fn_p_stChangeActionProcedure",
            "_fn_p_stChangeActionProcedure",
            "_fn_p_stChangeActionRandomProcedure",
            "_fn_p_stChangeActionProcedure",
            "_fn_p_stChangeActionProcedure",
            "_fn_p_stChangeActionProcedure",
            "_fn_p_stChangeActionRandomProcedure",
            "_fn_p_stChangeActionProcedure",
            "_fn_p_stLoopKeyWord",
            "_fn_p_stEndLoopKeyWord",
            "_fn_p_stBreakKeyword",
            "_fn_p_stMiscNoProcedure",
            "_fn_p_stMiscNoProcedure",
            "_fn_p_stMiscNoProcedure",
            "_fn_p_stMiscNoProcedure",
            "_fn_p_stMiscProcedure",
            "_fn_p_stMiscProcedure",
            "_fn_p_stMiscProcedure",
            "_fn_p_stMiscProcedure",
            "_fn_p_stMiscProcedure",
            "_fn_p_stMiscProcedure",
            "_fn_p_stMiscProcedure",
            "_fn_p_stMiscUltraProcedure",
            "_fn_p_stMiscUltraProcedure",
            "_fn_p_stMiscProcedure",
            "_fn_p_stMiscUltraProcedure",
            "_fn_p_stMiscMoreProcedure",
            "_fn_p_stLinkTableProcedure",
            "_fn_p_stLinkTableProcedure",
            "_fn_p_stLinkTableProcedure",
            "_fn_p_stBuildObjectTableFromTableAndStringProcedure",
            "_fn_p_stBuildObjectTableFromTableAndStringProcedure",
            "_fn_p_stModuleControlProcedure",
            "_fn_p_stModuleControlProcedure",
            "_fn_p_stModuleControlProcedure",
            "_fn_p_stSaveGameProcedure",
            "_fn_p_stChangeActivationChannelProcedure",
            "_fn_p_stChangeActivationChannelProcedure",
            "_fn_p_stPersoLightProcedure",
            "_fn_p_stPersoLightProcedure",
            "_fn_p_stPersoLightProcedure",
            "_fn_p_stPersoLightProcedure",
            "_fn_p_stPersoLightProcedure",
            "_fn_p_stPersoLightProcedure",
            "_fn_p_stPersoLightProcedure",
            "_fn_p_stPersoLightProcedure",
            "_fn_p_stPersoLightProcedure",
            "_fn_p_stPersoLightProcedure",
            "_fn_p_stPersoLightProcedure",
            "_fn_p_stDisplayProcedure",
            "_fn_p_stMenuAndVignetteProcedure",
            "_fn_p_stMenuAndVignetteProcedure",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_stTurnProcedure",
            "_fn_p_stTurnProcedure",
            "_fn_p_stTurnPersoProcedure",
            "_fn_p_stTurnPersoProcedure",
            "_fn_p_stKillPersoAndClearVariableProcedure",
            "_fn_p_stKillPersoAndClearVariableProcedure",
            "_fn_p_stDeletePersoFromGameProcedure",
            "_fn_p_stVisualMaterialProcedure",
            "_fn_p_stVisualMaterialProcedure",
            "_fn_p_stVisualMaterialProcedure",
            "_fn_p_stVisualMaterialProcedure",
            "_fn_p_stVisualMaterialProcedure",
            "_fn_p_stVisualMaterialProcedure",
            "_fn_p_stVisualMaterialProcedure",
            "_fn_p_stVisualMaterialProcedure",
            "_fn_p_stVisualMaterialProcedure",
            "_fn_p_stVisualMaterialProcedure",
            "_fn_p_stOptionChangerProc",
            "_fn_p_stOptionChangerProc",
            "_fn_p_stOptionChangerProc",
            "_fn_p_stOptionChangerProc",
            "_fn_p_stOptionChangerProc",
            "_fn_p_stOptionChangerProc",
            "_fn_p_stBatchSetPersoAtModulePosition",
            "_fn_p_stBatchSetPersoOrientation",
            "_fn_p_stBatchSynchroPersoWithPerso",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_stDynamProcedure",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc_ForReorientation",
            "_fn_p_st3DProc_ForReorientation",
            "_fn_p_st3DProc",
            "_fn_p_stCustomBitsProc",
            "_fn_p_stCustomBitsProc",
            "_fn_p_stCustomBitsProc",
            "_fn_p_stCustomValuesProc",
            "_fn_p_stCustomValuesProc",
            "_fn_p_stCustomValuesProc",
            "_fn_p_SetMechanicSpeedVector",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedVector",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedVector",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedVector",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_stFixePositionPerso",
            "_fn_p_stFixePositionPerso",
            "_fn_p_SetMechanicSpeedVector",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedVector",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_stPrepareMorph",
            "_fn_p_stPrepareMorphMT",
            "_fn_p_stStopMorph",
            "_fn_p_stStopMorph",
            "_fn_p_stMorphing",
            "_fn_p_stMorphingMT",
            "_fn_p_stModuleControlProcedure",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc",
            "_fn_p_st3DProc_ForReorientation",
            "_fn_p_st3DProc_ForReorientation",
            "_fn_p_st3DProc",
            "_fn_p_stCollideCommunicationProc",
            "_fn_p_stCollideCommunicationProc",
            "_fn_p_stCollideCommunicationProc",
            "_fn_p_stCollideCommunicationProc",
            "_fn_p_stCollideReinitCommunicationProc",
            "_fn_p_stResetLastCollisionActor",
            "_fn_p_stResetLastCollisionActor",
            "_fn_p_stMiscUltraProcedure",
            "_fn_p_stMiscUltraProcedure",
            "_fn_p_stChangeTextDefaultColor",
            "_fn_p_stCreateTextWithFormat",
            "_fn_p_stCreateTextWithFormat",
            "_fn_p_stStringProc",
            "_fn_p_stStringProc",
            "_fn_p_stStringProc",
            "_fn_p_stStringProc",
            "_fn_p_stIntToText",
            "_fn_p_stRealToText",
            "_fn_p_SetMechanicOption",
            "_fn_p_SetMechanicOption",
            "_fn_p_SetMechanicOption",
            "_fn_p_SetMechanicOption",
            "_fn_p_SetMechanicOption",
            "_fn_p_SetMechanicOption",
            "_fn_p_SetMechanicOption",
            "_fn_p_SetMechanicOption",
            "_fn_p_SetMechanicOption",
            "_fn_p_SetMechanicOption",
            "_fn_p_SetMechanicOption",
            "_fn_p_SetMechanicOption",
            "_fn_p_SetMechanicOption",
            "_fn_p_SetMechanicOption",
            "_fn_p_SetMechanicOption",
            "_fn_p_SetMechanicOption",
            "_fn_p_SetMechanicOption",
            "_fn_p_SetMechanicOption",
            "_fn_p_SetMechanicOption",
            "_fn_p_SetMechanicRealParameter",
            "_fn_p_SetMechanicRealParameter",
            "_fn_p_SetMechanicRealParameter",
            "_fn_p_SetMechanicRealParameter",
            "_fn_p_SetMechanicRealParameter",
            "_fn_p_SetMechanicRealParameter",
            "_fn_p_SetMechanicRealParameter",
            "_fn_p_SetMechanic3RealParameter",
            "_fn_p_SetMechanicRealParameter",
            "_fn_p_SetMechanicRealParameter",
            "_fn_p_SetMechanicRealParameter",
            "_fn_p_SetMechanicVectorParameter",
            "_fn_p_SetMechanicRealParameter",
            "_fn_p_SetMechanicVectorParameter",
            "_fn_p_SetMechanicRealParameter",
            "_fn_p_SetMechanicVectorParameter",
            "_fn_p_SetMechanicListParameter",
            "_fn_p_SetMechanicSpeedVector",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_PlatformLink",
            "_fn_p_PlatformLink",
            "_fn_p_SetMechanic3Real",
            "_fn_p_SetMechanic3Real",
            "_fn_p_SetMechanicRealParameter",
            "_fn_p_SetMechanicRealParameter",
            "_fn_p_SetMechanicRealParameter",
            "_fn_p_SetMechanicClimbSpeedLimit",
            "_fn_p_SetMechanicRealParameter",
            "_fn_p_SetMechanicSpeedReal",
            "_fn_p_SetMechanicRealParameter",
            "_fn_p_SetMechanicRealParameter",
            "_fn_p_HierFatherLink",
            "_fn_p_HierFatherLink",
            "_fn_p_HierFatherLink",
            "_fn_p_stMiscProcedure",
            "_fn_p_LinkControl",
            "_fn_p_stMiscProcedure",
            "_fn_p_stFixePositionZDx",
            "_fn_p_stFixePositionZDx",
            "_fn_p_stFixePositionZDx",
            "_fn_p_stChangeGameMaterialZDx",
            "_fn_p_stChangeLigthIntensity",
            "_fn_SPO_p_stChangeFlag",
            "_fn_SPO_p_stChangeFlag",
            "_fn_p_stChangeActorSpoFlag",
            "_fn_p_stChangeScreen",
            "_fn_p_stChangeScreen",
            "_fn_p_stChangeScreen",
            "_fn_p_stChangeScreen",
            "_fn_p_stChangeScreen",
            "_fn_p_stChangeScreen",
            "_fn_p_stShadow",
            "_fn_p_stShadow",
            "_fn_p_stShadow",
            "_fn_p_stSetPrivilegeActivationZDx",
            "_fn_p_stSetPrivilegeActivationZDx",
            "_fn_p_stSetPrivilegeActivationZDx",
            "_fn_p_stSetPrivilegeActivationZDx",
            "_fn_p_stSetPrivilegeActivationZDx",
            "_fn_p_stSetPrivilegeActivationZDx",
            "_fn_p_stSetPrivilegeActivationZDx",
            "_fn_p_stSetPrivilegeActivationZDx",
            "_fn_p_stSetPrivilegeActivationZDx",
            "_fn_p_stSetPrivilegeActivationZDx",
            "_fn_p_stSetPrivilegeActivationZDx",
            "_fn_p_stSetPrivilegeActivationZDx",
            "_fn_p_stActivationZDR",
            "_fn_p_stSetCollSetCollisionFlag",
            "_fn_p_stSetCollSetCollisionFlag",
            "_fn_p_stSetCollSetCollisionFlag",
            "_fn_p_stSetCollSetCollisionFlag",
            "_fn_p_stSetCollSetCollisionFlag",
            "_fn_p_stSetCollSetCollisionFlag",
            "_fn_p_stSetComputationFrequency",
            "_fn_p_stSetComputationFrequency",
            "_fn_p_stSetComputationFrequency",
            "_fn_p_stWorldMapProc",
            "_fn_p_stWorldMapProc",
            "_fn_p_stWorldMapProc",
            "_fn_p_stReadAnalogJoystickMario",
            "_fn_p_stSetAnalogJoystickAxes",
            "_fn_p_stSetAnalogJoystickAxes",
            "_fn_p_stSetAnalogJoystickAxes",
            "_fn_p_stSetAnalogJoystickAxes",
            "_fn_p_stSetAnalogJoystickAxes2",
            "_fn_p_stReleaseAnalogJoystick",
            "_fn_p_stSetBooleanInArray",
            "_fn_p_stSetDefaultFormatCharacter",
            "_fn_p_stSelectDriver",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_stSelectResolution",
            "_fn_p_stChangeBrightness",
            "_fn_p_stTextIntegerParameter",
            "_fn_p_stTextRealParameter",
            "_fn_p_stSetVideoOptions",
            "_fn_p_stSetVideoOptions",
            "_fn_p_stDummy",
            "_fn_p_stMiscProtectProcedure",
            "_fn_p_stShellExecuteProcedure",
            "_fn_p_stTemporalChangeSighting",
            "_fn_p_st_PAD2_Procedure",
            "_fn_p_st_PAD2_Procedure",
            "_fn_p_st_PAD2_Procedure",
            "_fn_p_st_PAD2_Procedure",
            "_fn_p_st_PAD2_Procedure",
            "_fn_p_st_PAD2_Procedure",
            "_fn_p_st_PAD2_Procedure",
            "_fn_p_st_InputProcedure",
            "_fn_p_stSHWSetShadowMode",
            "_fn_p_stSHWSetShadowMode",
            "_fn_p_stSHWSetShadowMode",
            "_fn_p_stValidateMemoryCard",
            "_fn_p_stAddMemoryCardString",
            "_fn_p_stMiscProcedure",
            "_fn_p_stCode4MagicPointsProcedures",
            "_fn_p_stCode4MagicPointsProcedures",
            "_fn_p_stCode4MagicPointsProcedures",
            "_fn_p_stCode4MagicPointsProcedures",
            "_fn_p_stCode4MagicPointsProcedures",
            "_fn_p_stCode4MagicPointsProcedures",
            "_fn_p_stCode4MagicPointsProcedures",
            "_fn_p_stCode4MagicPointsProcedures",
            "_fn_p_stCode4AirPointsProcedures",
            "_fn_p_stCode4AirPointsProcedures",
            "_fn_p_stCode4AirPointsProcedures",
            "_fn_p_stCode4AirPointsProcedures",
            "_fn_p_stCode4AirPointsProcedures",
            "_fn_p_stCode4AirPointsProcedures",
            "_fn_p_stCode4AirPointsProcedures",
            "_fn_p_stCode4AirPointsProcedures",
            "_fn_p_stFixePositionFade",
            "_fn_p_stSetLocalLight",
            "_fn_p_stSetLocalLightOnOff",
            "_fn_p_stSetLight",
            "_fn_p_stSetLight",
            "_fn_p_stSetLight",
            "_fn_p_stSetLight",
            "_fn_p_stSetLight",
            "_fn_p_stRLIProcedure",
            "_fn_p_stRLIProcedure",
            "_fn_p_stRLIProcedure",
            "_fn_p_stSetRadiusWP",
            "_fn_p_stSetCoordWP",
            "_fn_p_stSetCoordWP",
            "_fn_p_stMiscProcOnTypeOfWP",
            "_fn_p_stCapabilityProcedure",
            "_fn_p_stCapabilityProcedure",
            "_fn_p_stCapabilityProcedure",
            "_fn_p_stCapabilityProcedure",
            "_fn_p_stWPSetRangeValue",
            "_fn_p_stReinitGraphProcedure",
            "_fn_p_stSetScrollSpeed",
            "_fn_p_stSetScrollSpeed",
            "_fn_p_stSetScrollSpeed",
            "_fn_p_stSetScrollSpeed",
            "_fn_p_stManageFrame",
            "_fn_p_stManageFrame",
            "_fn_p_stFreezeAnim",
            "_fn_p_stFreezeAnim",
            "_fn_p_stSetDiscreetSpeed",
            "_fn_p_stSPOSuperimpoed",
            "_fn_p_stSPOSuperimpoed",
            "_fn_p_stSPOSuperimpoed",
            "_fn_p_stSPOSuperimpoed",
            "_fn_p_stSPOSuperimpoed",
            "_fn_p_stSPOSuperimpoed",
            "_fn_p_stSetOutlineMode",
            "_fn_p_stSetOutlineMode",
            "_fn_p_stSetSPOCoordinates",
            "_fn_p_stSetSPOCoordinates",
            "_fn_p_stSetSPOCoordinates",
            "_fn_p_stSetSPOCoordinates",
            "_fn_p_stSetSPOCoordinates",
            "_fn_p_stSetSPOCoordinates",
            "_fn_p_stSetSPOCoordinates",
            "_fn_p_stSetSPOCoordinates",
            "_fn_p_stSetSPOCoordinates",
            "_fn_p_stSetSPOCoordinates",
            "_fn_p_stSetSOLCoordinates_SPOParam",
            "_fn_p_stSetSOLCoordinates_SPOParam",
            "_fn_p_stSetSOLCoordinates_SPOParam",
            "_fn_p_stSetSOLCoordinates_SPOParam",
            "_fn_p_stSetSOLCoordinates_SPOParam",
            "_fn_p_stSetSOLCoordinates_SOLParam",
            "_fn_p_stSetSOLCoordinates_SOLParam",
            "_fn_p_stSetSOLCoordinates_SOLParam",
            "_fn_p_stSetSOLCoordinates_SOLParam",
            "_fn_p_stSetSOLCoordinates_SOLParam",
            "_fn_p_stSOLEdit",
            "_fn_p_stSOLEdit",
            "_fn_p_stSOLEdit",
            "_fn_p_stSOLEdit",
            "_fn_p_stSOLEdit",
            "_fn_p_stSOLEdit",
            "_fn_p_stSPOSuperimpoed",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotate",
            "_fn_p_stSPORotateToIdentity",
            "_fn_p_stSPOChangeSighting",
            "_fn_p_stSPOChangeSighting",
            "_fn_p_stSPOChangeSighting",
            "_fn_p_stSPOChangeSighting",
            "_fn_p_stSPOChangeSighting",
            "_fn_p_stSPOChangeSighting",
            "_fn_p_stSPOChangeSighting",
            "_fn_p_stSPOChangeSighting",
            "_fn_p_stSPOChangeSighting",
            "_fn_p_stSPOChangeSighting",
            "_fn_p_stTractionFactorProcedure",
            "_fn_p_stTurnToPosition",
            "_fn_p_stTurnToPosition",
            "_fn_p_stSortArray",
            "_fn_p_stActiveJoystickAnal",
            "_fn_p_stActiveJoystickAnal",
            "_fn_p_stSetZDxSize",
            "_fn_p_stSetZDxSize",
            "_fn_p_stCode4ChangeCaractere",
            "_fn_p_stCode4FormateTexte",
            "_fn_p_stCode4FormateTexte",
            "_fn_p_stChangePersoHorizSighting",
            "_fn_p_stPlayDemo",
            "_fn_p_stPlayAutoDemo",
            "_fn_p_stSetCharacterMaskedForResearch",
            "_fn_p_stInitKeyBoardDirections",
            "_fn_p_stInitKeyBoardPadButton",
            "_fn_p_stSetCenterPosition",
            "_fn_p_stSetMaximalValues",
            "_fn_p_stSetTooFarLimit",
            "_fn_p_stSetTransparencyZone",
            "_fn_p_stBaseFrequenceForMenu",
            "_fn_p_stSaveSinusEffectContext",
            "_fn_p_stSaveSinusEffectContext",
            "_fn_p_stTextSuperImposed",
            "_fn_p_stSubAnimProc",
            "_fn_p_stSubAnimProc",
            "_fn_p_stSubAnimProc",
            "_fn_p_stSubAnimProc",
            "_fn_p_stSubAnimProc",
            "_fn_p_stSubAnimProc",
            "_fn_p_stSubAnimProc",
            "_fn_p_stSHWSetDynShadow",
            "_fn_p_stSHWSetDynShadow",
            "_fn_p_stSHWSetDynShadow",
            "_fn_p_stPS2SetLanguageProc",
            "_fn_p_stCallSubRoutine",
            "_fn_p_stACTSetRangeValue",
            "_fn_p_stCode4InternalLights",
            "_fn_p_stCode4InternalLights",
            "_fn_p_stToggleCinemascope",
            "_fn_p_stToggleCinemascope",
            "_fn_p_stSetCinemascopeRatio",
            "_CAM_fn_p_stUpdatePosition",
            "_CAM_fn_p_stUpdatePosition2",
            "_CAM_fn_p_stChangeVectorParameter",
            "_CAM_fn_p_stChangeVectorParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeRealParameter",
            "_CAM_fn_p_stChangeTgtPerso",
            "_CAM_fn_p_stChangeSecondTgtPerso",
            "_CAM_fn_p_stChangeChannel",
            "_CAM_fn_p_stActivate",
            "_CAM_fn_p_stAssociateViewport",
            "_CAM_fn_p_stSetIAFlags",
            "_CAM_fn_p_stSetIAFlags",
            "_CAM_fn_p_stSetIAFlags",
            "_CAM_fn_p_stSetIAFlags",
            "_CAM_fn_p_stSetIAFlags",
            "_CAM_fn_p_stSetIAFlags",
            "_CAM_fn_p_stSetIAFlags",
            "_CAM_fn_p_stSetIAFlags",
            "_CAM_fn_p_stSetIAFlags",
            "_CAM_fn_p_stSetDNMFlags",
            "_CAM_fn_p_stSetDNMFlags",
            "_CAM_fn_p_stSetDNMFlags",
            "_CAM_fn_p_stSetDNMFlags",
            "_CAM_fn_p_stSetDNMFlags",
            "_CAM_fn_p_stSetDNMFlags",
            "_CAM_fn_p_stSetDNMFlags",
            "_CAM_fn_p_stSetDNMFlags",
            "_CAM_fn_p_stSetDNMFlags",
            "_CAM_fn_p_stSetDNMFlags",
            "_CAM_fn_p_stChangeConstants",
            "_CAM_fn_p_stConstants",
            "_CAM_fn_p_stConstants",
            "_CAM_fn_p_stShowInfo",
            "_CAM_fn_p_stSetForce",
            "_CAM_fn_p_stSetForce",
            "_CAM_fn_p_stSetForce",
            "_CAM_fn_p_stReset",
            "_CAM_fn_p_stForceBestPos",
            "_CAM_fn_p_stForceNormalState",
            "_CAM_fn_p_stForceMovingOnRail",
            "_CAM_fn_p_stCameraMode",
            "_CAM_fn_p_stCameraSetTransparencyFlag",
            "_fn_p_InitCamShooter",
            "_fn_p_RegisterDesignVar",
            "_fn_p_RegisterDesignVar",
            "_fn_p_RegisterDesignVar",
            "_fn_p_RegisterDesignVar",
            "_fn_p_RegisterDesignVar",
            "_fn_p_GetViewFinderVMT",
            "_fn_p_GetMainActorComports",
            "_fn_p_InitBackMode",
            "_fn_p_InitMarioMode",
            "_fn_p_InitStrafeLockMode",
            "_fn_p_AddMainActor",
            "_fn_p_RemoveMainActor",
            "_fn_p_SetSkin",
            "_fn_p_SetGCubeVersion",
            "_LNK_fn_p_InitAll",
            "_LNK_fn_p_SetAgo",
            "_LNK_fn_p_SetLag",
            "_LNK_fn_p_SetGaugeSpeed",
            "_LNK_fn_SetSendDataRate",
            "_LNK_fn_SetSendStatusPeriod",
            "_LNK_fn_SetLaunchSpeed",
            "_LNK_fn_SetFlagStraight",
            "_LNK_fn_SetUnlaunch",
            "_fn_p_stAGOProcedure",
            "_fn_p_stAGOProcedure",
            "_fn_p_stInGameMenuProcedure",
            "_fn_p_stJFFTXTProcedure",
            "_fn_p_stJFFTXTProcedure",
            "_fn_p_stJFFTXTProcedure",
            "_fn_p_stJFFTXTProcedure",
            "_fn_p_stJFFTXTProcedure",
            "_fn_p_stJFFTXTProcedure",
            "_fn_p_stJFFTXTProcedure",
            "_fn_p_stJFFTXTProcedure",
            "_fn_p_stJFFTXTProcedure",
            "_fn_p_stJFFTXTProcedure",
            "_fn_p_stJFFTXTProcedure",
            "_fn_p_stJFFTXTProcedure",
            "_fn_p_stJFFTXTSettings",
            "_fn_p_stJFFTXTSettings",
            "_fn_p_stJFFTXTSettings",
            "_fn_p_stJFFTXTSettings",
            "_fn_p_stJFFTXTSettings",
            "_fn_p_stJFFTXTGetBdBox",
            "_fn_p_stDummy",
            "_fn_p_stDummy",
            "_fn_p_stCheatCodeProcedure",
            "_fn_p_stCheatCodeProcedure",
            "_fn_p_stCheatCodeProcedure",
            "_fn_p_stCheatCodeProcedure",
            "_fn_p_stMultiPlayerProcedure",
            "_fn_p_stMultiPlayerProcedure",
            "_fn_p_stMultiPlayerProcedure",
            "_fn_p_stMultiPlayerProcedure",
            "_fn_p_stAGOProcedure",
            "_fn_p_stAGOProcedure",
            "_fn_p_stAGOProcedure",
            "_fn_p_stAGOProcedure",
            "_fn_p_stJFFTXTProcedure",
            "_fn_p_stJFFTXTProcedure",
            "_fn_p_stJFFTXTProcedure",
            "_fn_p_stMultiPlayerProcedure",
            "_fn_p_stMultiPlayerProcedure",
            "_fn_p_st_SinusEffect_SetPreMultiplier",
            "_fn_p_stAGOProcedure",
            "_fn_p_stAGOProcedure",
            "_fn_p_stAGOProcedure",
            "_fn_p_stLogWindowProcedure",
            "_fn_p_stRLIProcedure2",
            "_fn_p_stRLIProcedure2",
            "_fn_p_stRLIProcedure2",
            "_fn_p_stVideoProcedure",
            "_fn_p_stVideoProcedure",
            "_fn_p_stVideoProcedure",
            "_fn_p_stVideoProcedure",
            "_fn_p_stSetVSyncWait",
            "_fn_p_stBrainActivationProcedure",
            "_fn_p_stBrainActivationProcedure",
            "_fn_p_stDisplaySegment",
            "_fn_p_stEndTransitionProcedure",
            "_fn_p_stStartCine",
            "_fn_p_stStartCine",
            "_fn_p_stLoadingLevel",
            "_fn_p_stDataPath",
            "_fn_p_stSAV2SaveProcedure",
            "_fn_p_stSAV2SaveProcedure",
            "_fn_p_stSAV2SaveProcedure",
            "_fn_p_stSAV2SaveProcedure",
            "_fn_p_stSAV2SaveProcedure",
            "_fn_p_stSAV2SaveProcedure",
            "_fn_p_stSAV2SaveProcedure",
            "_fn_p_stSAV2SaveProcedure",
            "_fn_p_stSAV2SaveProcedure",
            "_fn_p_stSAV2SaveProcedure",
            "_fn_p_stSAV2SaveProcedure",
            "_fn_p_stSAV2SaveProcedure",
            "_fn_p_stSAV2SaveProcedure",
            "_fn_p_stSAV2SaveProcedure",
            "_fn_p_stSAV2SaveProcedure",
            "_fn_p_stSAV2SaveProcedure",
            "_fn_p_stSAV2SaveProcedure",
            "_fn_p_stSAV2SaveProcedure",
            "_fn_p_stSAV2SaveProcedure",
            "_fn_p_stSCT_UltraProcedure",
            "_fn_p_stSCT_UltraProcedure",
            "_fn_p_stPortalActivationProcedure",
            "_fn_p_stPortalActivationProcedure",
            "_fn_p_stLogFileProcedure",
            "_fn_p_stLogFileProcedure",
            "_fn_p_stLogFileProcedure",
            "_fn_p_stFFBProcedures",
            "_fn_p_stFFBProcedures",
            "_fn_p_stFFBProcedures",
            "_fn_p_stFFBProcedures",
            "_fn_p_stFFBProcedures",
            "_fn_p_stFFBProcedures",
            "_fn_p_stFFBProcedures",
            "_fn_p_stFFBProcedures",
            "_fn_p_stFFBProcedures",
            "_fn_p_stFFBProcedures",
            "_fn_p_stSoundProcedure",
            "_fn_p_stSoundProcedure",
            "_fn_p_stSoundProcedure",
            "_fn_p_stSoundProcedure",
            "_fn_p_stSoundProcedureSendRequest",
            "_fn_p_stSoundProcedureSendRequest",
            "_fn_p_stSoundProcedureSendRequest",
            "_fn_p_stSoundProcedureSendRequest",
            "_fn_p_stSoundProcedureSendRequest",
            "_fn_p_stSoundProcedureSendRequest",
            "_fn_p_stSoundProcedureSendRequest",
            "_fn_p_stSoundProcedureSendRequest",
            "_fn_p_stSoundProcedureSendRequest",
            "_fn_p_stSoundProcedureSendRequest",
            "_fn_p_stSoundProcedureSendRequest",
            "_fn_p_stSoundProcedureSendRequest",
            "_fn_p_stSoundProcedureSendRequest",
            "_fn_p_stSoundProcedureSendRequest",
            "_fn_p_stSoundProcedureChangeVolumeId",
            "_fn_p_stSoundProcedureChangeVolumeId",
            "_fn_p_stSoundProcedureChangeVolumeId",
            "_fn_p_stSoundProcedureStopRequest",
            "_fn_p_stSoundProcedureStopRequest",
            "_fn_p_stSoundProcedureStopRequest",
            "_fn_p_stSoundProcedureStopRequest",
            "_fn_p_stSoundProcedureStopRequest",
            "_fn_p_stSoundProcedureStopRequest",
            "_fn_p_stLipsChannelControl",
            "_fn_p_stLipsChannelControl",
            "_fn_p_stSoundProcedure",
            "_fn_p_stSoundProcedure",
            "_fn_p_stSoundProcedure",
            "_fn_p_stSoundProcedure",
            "_fn_p_stSoundProcedureSetVolume",
            "_fn_p_stSoundProcedureSetVolume",
            "_fn_p_stSoundProcedureSetVolume",
            "_fn_p_stSoundProcedureSetVolume",
            "_fn_p_stSoundProcedureSetVolume",
            "_fn_p_stSoundProcedureChangeVolume",
            "_fn_p_stSoundProcedureChangeVolume",
            "_fn_p_stSoundProcedureChangeVolume",
            "_fn_p_stSoundProcedureChangeVolume",
            "_fn_p_stSoundProcedureChangeVolume",
            "_fn_p_stSoundProcedurePause",
            "_fn_p_stSoundProcedurePause",
            "_fn_p_stSoundProcedurePause",
            "_fn_p_stSoundProcedurePause",
            "_fn_p_stSoundProcedurePause",
            "_fn_p_stSoundProcedurePause",
            "_fn_p_stSoundProcedureResume",
            "_fn_p_stSoundProcedureResume",
            "_fn_p_stSoundProcedureResume",
            "_fn_p_stSoundProcedureResume",
            "_fn_p_stSoundProcedureResume",
            "_fn_p_stSoundProcedureResume",
            "_fn_p_stSetDopplerEffect",
            "_fn_p_stSetInStereoMode",
            "_fn_p_stSetPrevMusicFadeOut",
            "_fn_p_stSetRollOffDistances",
            "_fn_p_stSetRollOffDistances",
            "_fn_p_stSaveCurrentSoundRequest",
            "_fn_p_stSaveCurrentSoundRequest",
            "_fn_p_stMusicMarkerSlotControlProcedure",
            "_fn_p_stSoundProcedurePS2ChangeReverb",
            "_fn_p_stSoundProcedurePS2SetReverbOn",
            "_fn_p_stSoundProcedureSendRequest",
            "_fn_p_stSetGameMode",
            "_fn_p_stSetGameMode",
            "_fn_p_stDoNotLoadTextures",
            "_fn_p_stVisualMaterialProcedure",
            "_fn_p_stHandleFamilyDynamicLoad",
            "_fn_p_stHandleActorDynamicLoad",
            "_fn_p_stMonitoringStart",
            "_fn_p_stMonitoringStop",
            "_fn_p_stCreateToby",
            "_fn_p_stAddSegmentToToby",
            "_fn_p_stTobySetTransparency",
            "_fn_p_stTobyDestroy",
            "_fn_p_stTobySetMaterial",
            "_fn_p_stScreenProc",
            "_fn_p_stScreenProc",
            "_fn_p_stScreenProc",
            "_fn_p_stMCProc",
            "_fn_p_stBulletTimeProc",
            "_fn_p_stDemoProc",
            "_fn_p_stSetCurrentValueAsInit",
            "_fn_p_stSetCheapCharacterDistance",
            "_fn_p_stSetCheapCharacterDistance",
            "_fn_p_stSetCheapCharacterTimer",
            "_fn_p_stSetCheapCharacterRefObj",
            "_fn_p_stSetCheapCharacterMode",
            "_fn_p_stSetCheapCharacterListAura",
            "_fn_p_stSetCheapCharacterPos",
            "_fn_p_stSetCheapCharacterPos",
            "_fn_p_stAddCheapCharacter",
            "_fn_p_stResetCheapCharacterList",
            "_fn_p_stActivateCheapCharacter",
            "_fn_p_stActivateCheapCharacter",
            "_fn_p_stSetCheapCharacterOptions",
            "_fn_p_stR3SetValue",
            "_fn_p_stR3SetValue",
            "_fn_p_stR3SetValue",
            "_fn_p_stR3SetValue",
            "_fn_p_stR3SetValue",
            "_fn_p_stR3SetValue",
            "_fn_p_stR3SetValue",
            "_fn_p_stWaterEffect_SetRandomPerturbationGeneration",
            "_fn_p_stWaterEffect_GenerateImpulse",
            "_fn_p_stWaterEffect_GenerateSplash",
            "_fn_p_stAGOProcedure",
            "_fn_p_stAGOProcedure",
            "_fn_p_stTakePictureProcedure",
            "_fn_p_stTakePictureProcedure",
            "_fn_p_stSFX_ActivateLightReflection",
            "_fn_p_stSFX_ActivateWaterCircles",
            "_fn_p_stGcSetActiveMcSlot",
            "_fn_p_stGcResetToIpl",
            "_fn_p_stChangeActionProcedure",
            "_fn_p_stChangeActionProcedure",
            "_fn_p_stChangeActionProcedure",
            "_fn_p_st2DMenuProcedure",
            "_fn_p_st2DMenuProcedure",
            "_fn_p_st2DMenuProcedure",
            "_fn_p_st2DMenuProcedure",
            "_fn_p_st2DMenuProcedure",
            "_fn_p_stAllowNormalsRecomputing"
        });
        #endregion

        #region Conditions
        public static List<string> conditionTable = new List<string>(new string[] {
            "_fn_p_stBooleanCondition",
            "_fn_p_stBooleanCondition",
            "_fn_p_stBooleanCondition",
            "_fn_p_stBooleanCondition",
            "_fn_p_stComparisonCondition",
            "_fn_p_stComparisonCondition",
            "_fn_p_stComparisonCondition",
            "_fn_p_stComparisonCondition",
            "_fn_p_stComparisonCondition",
            "_fn_p_stComparisonCondition",
            "_fn_p_stZDDCondition",
            "_fn_p_stZDDCondition",
            "_fn_p_stZDDCondition",
            "_fn_p_stZDDCondition",
            "_fn_p_stZDDCondition",
            "_fn_p_stZDECondition",
            "_fn_p_stZDECondition",
            "_fn_p_stZDECondition",
            "_fn_p_stZDECondition",
            "_fn_p_stZDECondition",
            "_fn_p_stZDECondition",
            "_fn_p_stZDECondition",
            "_fn_p_stZDECondition",
            "_fn_p_stZDECondition",
            "_fn_p_stZDECondition",
            "_fn_p_stZDECondition",
            "_fn_p_stZDECondition",
            "_fn_p_stReportOnSurfaceCondition",
            "_fn_p_stReportOnSurfaceCondition",
            "_fn_p_stReportOnSurfaceCondition",
            "_fn_p_stReportOnSurfaceCondition",
            "_fn_p_stReportOnSurfaceCondition",
            "_fn_p_stReportOnSurfaceCondition",
            "_fn_p_stReportThisPerso",
            "_fn_p_stReportOnZDMSurfaceCondition",
            "_fn_p_stReportOnZDMSurfaceCondition",
            "_fn_p_stReportOnZDMSurfaceCondition",
            "_fn_p_stReportOnZDMSurfaceCondition",
            "_fn_p_stListCondition",
            "_fn_p_stListCondition",
            "_fn_p_stListCondition",
            "_fn_p_stListCondition",
            "_fn_p_st_UserEvent_IsSet",
            "_fn_p_st_UserEvent_IsSet",
            "_fn_p_st_UserEvent_IsSet",
            "_fn_p_stButtonCondition",
            "_fn_p_stButtonCondition",
            "_fn_p_stButtonCondition",
            "_fn_p_stButtonCondition",
            "_fn_p_stTimeCondition",
            "_fn_p_stValidityCondition",
            "_fn_p_stValidityCondition",
            "_fn_p_stValidityCondition",
            "_fn_p_stValidityCondition",
            "_fn_p_stValidityCondition",
            "_fn_p_stValidityCondition",
            "_fn_p_stValidityCondition",
            "_fn_p_stValidityCondition",
            "_fn_p_stSectorCondition",
            "_fn_p_st_ActivationCondition",
            "_fn_p_st_HandledCondition",
            "_fn_p_stAlw_IsMine",
            "_fn_p_stLightCondition",
            "_fn_p_stLightCondition",
            "_fn_p_stLightCondition",
            "_fn_p_stRLITransitionCondition",
            "_fn_p_stAlwaysActiveCond",
            "_fn_p_stAlwaysActiveCond",
            "_fn_p_stInputCondition",
            "_fn_p_stInputCondition",
            "_fn_p_stSAV2Condition",
            "_fn_p_stScreenCondition",
            "_fn_p_stScreenCondition",
            "_fn_p_stZDMCollideWithObstacle",
            "_fn_p_stZDMCollideWithObstacle",
            "_fn_p_stZDMCollideWithObstacle",
            "_fn_p_stZDMCollideWithObstacle",
            "_fn_p_stMiscCondition",
            "_fn_p_stMiscCondition",
            "_fn_p_stMiscCondition",
            "_fn_p_stMiscCondition",
            "_fn_p_stMiscCondition",
            "_fn_p_stCheckAnimEnd",
            "_fn_p_stMiscCondition",
            "_fn_p_stMiscCondition",
            "_fn_p_stMiscCondition",
            "_fn_p_stCollisionWP",
            "_fn_p_stCustomBitsCond",
            "_fn_p_stIsPersoActive",
            "_fn_p_stCheckAnimEnd",
            "_fn_p_stCustomBitsCond",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stMechanicOption",
            "_fn_p_stNullVector",
            "_fn_p_stHierarchySon",
            "_fn_p_stIsMorphing",
            "_fn_p_stCheckAnimEnd",
            "_fn_p_stCheckAnimSmooth",
            "_fn_p_stCheckCapabilities",
            "_fn_p_stCheckCapabilities",
            "_fn_p_stCheckCapabilities",
            "_fn_p_stCheckCapabilities",
            "_fn_p_stCheckCapabilities",
            "_fn_p_stCheckCapabilities",
            "_fn_p_stDummyCondition",
            "_fn_p_stIsCollisionFlag",
            "_fn_p_stIsCollisionFlag",
            "_fn_p_stIsCollisionFlag",
            "_fn_p_stIsCollisionFlag",
            "_fn_p_stIsCollisionFlag",
            "_fn_p_stIsOf",
            "_fn_p_stIsOf",
            "_fn_p_stAJoypadIsConnected",
            "_fn_p_stAKeyJustPressed",
            "_fn_p_stAButtonPadJustPressed",
            "_fn_p_stDemoCondition",
            "_fn_p_stDummyCondition",
            "_fn_p_stTooFarCondition",
            "_fn_p_stCheckSubAnim",
            "_fn_p_stCheckCustomBitSubAnim",
            "_fn_p_stCheckSubAnim",
            "_fn_p_stCheckSubAnim",
            "_fn_p_stComparisonOfObjectsCondition",
            "_fn_p_stButtonCondition",
            "_fn_p_stButtonCondition",
            "_fn_p_stButtonCondition",
            "_fn_p_stButtonCondition",
            "_fn_p_stCineIsPlaying",
            "_fn_p_stLoadInProgress",
            "_fn_p_stCheckSAV2LastError",
            "_fn_p_stCheckMCStatus",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_CAM_fn_p_stIs",
            "_fn_p_stIsInStereoMode",
            "_fn_p_stIsTypePlaying",
            "_fn_p_stIsTypePlaying",
            "_fn_p_stIsEventValid"
        });
        #endregion

        #region DsgVar Types
        public static List<DsgVarInfoEntry.DsgVarType> dsgVarTypeTable = new List<DsgVarInfoEntry.DsgVarType>(new DsgVarInfoEntry.DsgVarType[] {
            DsgVarInfoEntry.DsgVarType.Boolean,
            DsgVarInfoEntry.DsgVarType.Byte,
            DsgVarInfoEntry.DsgVarType.UByte, // Unsigned
            DsgVarInfoEntry.DsgVarType.Short,
            DsgVarInfoEntry.DsgVarType.UShort, // Unsigned
            DsgVarInfoEntry.DsgVarType.Int,
            DsgVarInfoEntry.DsgVarType.UInt, // Unsigned
            DsgVarInfoEntry.DsgVarType.Float,
            DsgVarInfoEntry.DsgVarType.Vector,
            DsgVarInfoEntry.DsgVarType.List,
            DsgVarInfoEntry.DsgVarType.Comport,
            DsgVarInfoEntry.DsgVarType.Action,
            DsgVarInfoEntry.DsgVarType.Caps,
            DsgVarInfoEntry.DsgVarType.Input,
            DsgVarInfoEntry.DsgVarType.SoundEvent,
            DsgVarInfoEntry.DsgVarType.Light,
            DsgVarInfoEntry.DsgVarType.GameMaterial,
            DsgVarInfoEntry.DsgVarType.VisualMaterial,
            DsgVarInfoEntry.DsgVarType.Perso,
            DsgVarInfoEntry.DsgVarType.Waypoint,
            DsgVarInfoEntry.DsgVarType.Graph,
            DsgVarInfoEntry.DsgVarType.Text,
            DsgVarInfoEntry.DsgVarType.SuperObject,
            DsgVarInfoEntry.DsgVarType.SOLinks,
            DsgVarInfoEntry.DsgVarType.Array1,
            DsgVarInfoEntry.DsgVarType.Array2,
            DsgVarInfoEntry.DsgVarType.Array3,
            DsgVarInfoEntry.DsgVarType.Array4,
            DsgVarInfoEntry.DsgVarType.Array5,
            DsgVarInfoEntry.DsgVarType.Array6,
            DsgVarInfoEntry.DsgVarType.Array7,
            DsgVarInfoEntry.DsgVarType.Array8,
            DsgVarInfoEntry.DsgVarType.Array9,
            DsgVarInfoEntry.DsgVarType.Array10,
            DsgVarInfoEntry.DsgVarType.Array11
        });
        #endregion

        public static ScriptNode.NodeType getNodeType(byte functionType) {

            switch (functionType) {
                case 0: // KeyWordFunctionPtr
                    return ScriptNode.NodeType.KeyWord;
                case 1: // GetConditionFunctionPtr
                    return ScriptNode.NodeType.Condition;
                case 2: // GetOperatorFunctionPtr
                    return ScriptNode.NodeType.Operator;
                case 3: // GetFunctionFunctionPtr
                    return ScriptNode.NodeType.Function;
                case 4: // ProcedureFunctionReturn
                    return ScriptNode.NodeType.Procedure;
                case 5: // meta action
                    return ScriptNode.NodeType.MetaAction;
                case 6:
                    return ScriptNode.NodeType.BeginMacro;
                case 7:
                    return ScriptNode.NodeType.BeginMacro;
                case 8:
                    return ScriptNode.NodeType.EndMacro;
                case 9:
                    return ScriptNode.NodeType.Field;
                case 10:
                case 11:
                    return ScriptNode.NodeType.DsgVarRef;
                case 12:
                    return ScriptNode.NodeType.Constant;
                case 13:
                    return ScriptNode.NodeType.Real;
                case 14:
                    return ScriptNode.NodeType.Button;
                case 15:
                    return ScriptNode.NodeType.ConstantVector;
                case 16:
                    return ScriptNode.NodeType.Vector;
                case 17:
                    return ScriptNode.NodeType.Mask;
                case 18:
                    return ScriptNode.NodeType.ModuleRef;
                case 19:
                    return ScriptNode.NodeType.DsgVarId;
                case 20:
                    return ScriptNode.NodeType.String;
                case 21:
                    return ScriptNode.NodeType.LipsSynchroRef;
                case 22:
                    return ScriptNode.NodeType.FamilyRef;
                case 23:
                    return ScriptNode.NodeType.PersoRef;
                case 24:
                    return ScriptNode.NodeType.ActionRef;
                case 25:
                    return ScriptNode.NodeType.SuperObjectRef;
                case 26:
                    return ScriptNode.NodeType.WayPointRef;
                case 27:
                    return ScriptNode.NodeType.TextRef;
                case 28:
                    return ScriptNode.NodeType.ComportRef;
                case 29:
                    return ScriptNode.NodeType.ModuleRef;
                case 30:
                    return ScriptNode.NodeType.SoundEventRef;
                case 31:
                    return ScriptNode.NodeType.ObjectTableRef;
                case 32:
                    return ScriptNode.NodeType.GameMaterialRef;
                case 33:
                    return ScriptNode.NodeType.ParticleGenerator;
                case 34:
                    return ScriptNode.NodeType.VisualMaterial;
                case 35:
                    return ScriptNode.NodeType.Color;
                case 36:
                    return ScriptNode.NodeType.DataType42;
                case 37:
                    return ScriptNode.NodeType.Light;
                case 38:
                    return ScriptNode.NodeType.Caps;
                case 39:
                    return ScriptNode.NodeType.SubRoutine;
                case 44:
                    return ScriptNode.NodeType.GraphRef;
            }

            return ScriptNode.NodeType.Unknown;
        }

        public static string readableFunctionSubType(ScriptNode sn, Perso perso) {
            MapLoader l = MapLoader.Loader;
            byte functionType = sn.type;
            int param = (int)sn.param;
            short mask = 0;

            Vector3 vector3 = new Vector3 { x = 0, y = 0, z = 0 };

            switch (functionType) {
                case 0: // KeyWordFunctionPtr
                    if (param < keywordTable.Count) { return keywordTable[param] + "(" + param + ")"; }
                    return "Unknown Keyword";
                case 1: // GetConditionFunctionPtr
                    if (param < conditionTable.Count) { return conditionTable[param] + "(" + param + ")"; }
                    return "Unknown Condition";
                case 2: // GetOperatorFunctionPtr
                    if (param < operatorTable.Count) { return operatorTable[param] + "(" + param + ")"; }
                    return "Unknown Operator";
                case 3: // GetFunctionFunctionPtr
                    if (param < functionTable.Count) { return functionTable[param] + "(" + param + ")"; }
                    return "Unknown Function";
                case 4: // ProcedureFunctionReturn
                    if (param < procedureTable.Count) { return procedureTable[param] + "(" + param + ")"; }
                    return "Unknown Procedure";
                case 5: // meta action
                    return "Meta Action";
                case 6:
                    return "Begin Macro";
                case 7:
                    return "Begin Macro";
                case 8:
                    return "End Macro";
                case 9:
                    return "EvalField";
                case 10:
                case 11:
                    string dsgVarString = "";
                    if (perso.brain.mind.dsgMem != null && perso.brain.mind.dsgMem.dsgVar != null
                        && perso.brain.mind.dsgMem.dsgVar.dsgVarInfos != null
                        && param < perso.brain.mind.dsgMem.dsgVar.dsgVarInfos.Length) {
                        DsgVarInfoEntry info = perso.brain.mind.dsgMem.dsgVar.dsgVarInfos[param];
                        if (info != null) {
                            dsgVarString += " (type " + info.type + ", value " + info.value + ")";
                        } else {
                            dsgVarString += " (not found)";
                        }
                    }
                    return "DsgVarRef: " + param + dsgVarString;
                case 12:

                    return "Constant: " + param;
                case 13:

                    return "Real: " + BitConverter.ToSingle(BitConverter.GetBytes(param), 0);
                case 14:
                    return "Button: " + "0x" + param.ToString("x8");
                case 15:
                    return "Constant Vector: " + "0x" + param.ToString("x8"); // TODO: get from address
                case 16:
                    return "Vector: " + "0x" + param.ToString("x8"); // TODO: same
                case 17:
                    mask = (short)param; // TODO: as short
                    return "Mask: " + (mask).ToString("x4");
                case 18:
                    return "ModuleRef: " + "0x" + (param).ToString("x8");
                case 19:
                    return "DsgVarId: " + "0x" + (param).ToString("x8");
                case 20:
                    string str = "ERR_STRING_NOTFOUND";
                    if (l.strings.ContainsKey(sn.param_ptr)) str = l.strings[sn.param_ptr];
                    return "String: " + sn.param_ptr + " (" + str + ")";
                case 21:
                    return "LipsSynchroRef: " + sn.param_ptr;
                case 22:
                    return "FamilyRef: " + sn.param_ptr;
                case 23:
                    return "PersoRef: " + sn.param_ptr;
                case 24:
                    State state = State.FromOffset(sn.param_ptr);
                    string stateName = state == null ? "ERR_STATE_NOTFOUND" : state.name;
                    return "ActionRef: " + sn.param_ptr + " (" + stateName + ")";
                case 25:
                    return "SuperObjectRef: " + sn.param_ptr;
                case 26:
                    return "WayPointRef: " + sn.param_ptr;
                case 27:
                    return "TextRef: " + sn.param_ptr;
                case 28:
                    return "ComportRef: " + sn.param_ptr;
                case 29:
                    return "ModuleRef: " + sn.param_ptr;
                case 30:
                    return "SoundEventRef: " + sn.param_ptr;
                case 31:
                    return "ObjectTableRef: " + sn.param_ptr;
                case 32:
                    return "GameMaterialRef: " + sn.param_ptr;
                case 33:
                    return "ParticleGenerator: " + "0x" + (param).ToString("x8");
                case 34:
                    return "VisualMaterial: " + sn.param_ptr;
                case 35:
                    return "Color: " + "0x" + (param).ToString("x8");
                case 36:
                    return "EvalDataType42: " + "0x" + (param).ToString("x8");
                case 37:
                    return "Light: " + "0x" + (param).ToString("x8");
                case 38:
                    return "Caps: " + "0x" + (param).ToString("x8");
                case 39:
                    return "Eval SubRoutine";
            }

            return "unknown";
        }
    }
}
