namespace BinarySerializer.Ubisoft.CPA {
	// Find: (NU_)?M_DEFINE_[^ \t\(]*[ \t]*\([ \t]*e[^_]*_([^ \t,]*)[ \t]*,[ \t]*([^ \t,]*)[ \t]*,([ \t]*([^ \t,]*)[ \t]*,)?[ \t]*([^ \t,]*)[ \t]*,[ \t]*fn_.*
	// Replace: \[Definition\(SCR: \6, EN: \5, FR: \3\)] \2,
	public enum AI_MetaAction {
		Placeholder,

		#region DefAct
		[AI_Definition(SCR: "Action_FrozenWait", EN: "TIME_FrozenWait", FR: "Temps_AttenteFigee")] FrozenWait,
		[AI_Definition(SCR: "Action_ExecuteAction", EN: "ACTION_ExecuteAction", FR: "ExecuteAction")] ExecuteAction,
		[AI_Definition(SCR: "Action_WaitEndOfAction", EN: "ACTION_WaitEndOfAction", FR: "AttendFinAction")] WaitEndOfAction,
		[AI_Definition(SCR: "Action_WaitEndOfAnim", EN: "ACTION_WaitEndOfAnim", FR: "AttendFinAnim")] WaitEndOfAnim,

		[AI_Definition(SCR: "Action_SpeakAndWaitEnd", EN: "ACTION_SpeakAndWaitEnd", FR: "ParleEtAttendLaFin")] SpeakAndWaitEnd,
		#endregion

		#region DefActCa
		[AI_Definition(SCR: "Action_CAM_CineMoveAToBTgtC", EN: "CAM_CineMoveAToBTgtC", FR: "CAM_CineMoveAToBTgtC")] CamCineMoveAToBTgtC,
		[AI_Definition(SCR: "Action_CAM_CineMoveAToBTgtAC", EN: "CAM_CineMoveAToBTgtAC", FR: "CAM_CineMoveAToBTgtAC")] CamCineMoveAToBTgtAC,
		[AI_Definition(SCR: "Action_CAM_CinePosATgtB", EN: "CAM_CinePosATgtB", FR: "CAM_CinePosATgtB")] CamCinePosATgtB,
		[AI_Definition(SCR: "Action_CAM_CinePosAMoveTgtBToC", EN: "CAM_CinePosAMoveTgtBToC", FR: "CAM_CinePosAMoveTgtBToC")] CamCinePosAMoveTgtBToC,

		[AI_Definition(SCR: "Action_CAM_CinePosATgtBTurnPosH", EN: "CAM_CinePosATgtBTurnPosH", FR: "CAM_CinePosATgtBTurnPosH")] CamCinePosATgtBTurnPosH,
		[AI_Definition(SCR: "Action_CAM_CinePosATgtBTurnTgtH", EN: "CAM_CinePosATgtBTurnTgtH", FR: "CAM_CinePosATgtBTurnTgtH")] CamCinePosATgtBTurnTgtH,
		[AI_Definition(SCR: "Action_CAM_CinePosATgtBTurnPosV", EN: "CAM_CinePosATgtBTurnPosV", FR: "CAM_CinePosATgtBTurnPosV")] CamCinePosATgtBTurnPosV,
		[AI_Definition(SCR: "Action_CAM_CinePosATgtBTurnTgtV", EN: "CAM_CinePosATgtBTurnTgtV", FR: "CAM_CinePosATgtBTurnTgtV")] CamCinePosATgtBTurnTgtV,
		#endregion

		#region R3 PS2
		[AI_Definition(SCR: "Action_ExecuteActionSmooth", EN: "ACTION_ExecuteActionSmooth", FR: "ExecuteActionSmooth")] ExecuteActionSmooth,
		#endregion

		#region Hype PS2 (SCR definitions from TT SE)
		[AI_Definition(SCR: "Action_IncrementalTurn2")] IncrementalTurn2,
		[AI_Definition(SCR: "Action_IncrementalTurn")] IncrementalTurn,
		[AI_Definition(SCR: "Action_Pursuit")] Pursuit,
		[AI_Definition(SCR: "Action_DeltaPursuit")] DeltaPursuit,
		[AI_Definition(SCR: "Action_ExecuteActionPerso")] ExecuteActionPerso,
		[AI_Definition(SCR: "Action_WaitEndOfActionPerso")] WaitEndOfActionPerso,
		[AI_Definition(SCR: "Action_WaitEndOfAnimPerso")] WaitEndOfAnimPerso,
		[AI_Definition(SCR: "Action_LSY_SpeakPersoAndWaitEnd")] LSY_SpeakPersoAndWaitEnd,
		[AI_Definition(SCR: "Action_ExecuteActionAndTakeObject")] ExecuteActionAndTakeObject,
		[AI_Definition(SCR: "Action_ExecuteActionAndPutObject")] ExecuteActionAndPutObject,
		[AI_Definition(SCR: "Action_ExecuteActionAndLaunchObject")] ExecuteActionAndLaunchObject,
		[AI_Definition(SCR: "Action_ExecuteActionAndGenerateObject")] ExecuteActionAndGenerateObject,
		[AI_Definition(SCR: "Action_AdjustPersoOnObjectAxes")] AdjustPersoOnObjectAxes,
		[AI_Definition(SCR: "Action_AdjustPersoOnObject")] AdjustPersoOnObject,
		[AI_Definition(SCR: "Action_RunAway")] RunAway,
		[AI_Definition(SCR: "Action_IncrementalTurnPosition")] IncrementalTurnPosition,
		[AI_Definition(SCR: "Action_IncrementalDeltaTurnPerso2")] IncrementalDeltaTurnPerso2,
		[AI_Definition(SCR: "Action_IncrementalTurnPerso2")] IncrementalTurnPerso2,
		[AI_Definition(SCR: "Action_IncrementalDeltaTurnPerso")] IncrementalDeltaTurnPerso,
		[AI_Definition(SCR: "Action_IncrementalTurnPerso")] IncrementalTurnPerso,
		[AI_Definition(SCR: "Action_RunAwayWP")] RunAwayWP,
		[AI_Definition(SCR: "Action_GoToWP")] GoToWP,
		[AI_Definition(SCR: "Action_GoToWPXY")] GoToWPXY,
		[AI_Definition(SCR: "Action_GoOverWay")] GoOverWay,
		[AI_Definition(SCR: "Action_GoOverWay3D")] GoOverWay3D,
		[AI_Definition(SCR: "Action_GoOverWayBack")] GoOverWayBack,
		[AI_Definition(SCR: "Action_GoToNextWPOfWay")] GoToNextWPOfWay,
		[AI_Definition(SCR: "Action_GoToNextWPOfWayBack")] GoToNextWPOfWayBack,
		[AI_Definition(SCR: "Action_GoToPosition")] GoToPosition,
		[AI_Definition(SCR: "Action_GoToPositionXY")] GoToPositionXY,
		[AI_Definition(SCR: "Action_GoOverShortestPath")] GoOverShortestPath,
		[AI_Definition(SCR: "Action_GoOverShortestPathBezier")] GoOverShortestPathBezier,
		[AI_Definition(SCR: "Action_MoveLift")] MoveLift,
		[AI_Definition(SCR: "Action_Wait")] Wait,
		[AI_Definition(SCR: "Action_WaitBoolean")] WaitBoolean,
		[AI_Definition(SCR: "Action_WaitNextTime")] WaitNextTime,
		[AI_Definition(SCR: "Action_WaitInteger")] WaitInteger,
		[AI_Definition(SCR: "Action_WaitReal")] WaitReal,
		[AI_Definition(SCR: "Action_IncrementalTurnPositionW")] IncrementalTurnPositionW,
		[AI_Definition(SCR: "Action_IncrementalTurnPositionWPerso")] IncrementalTurnPositionWPerso,
		[AI_Definition(SCR: "Action_IncrementalTurnPersoW")] IncrementalTurnPersoW,
		[AI_Definition(SCR: "Action_IncrementalTurnPersoWPerso")] IncrementalTurnPersoWPerso,
		[AI_Definition(SCR: "Action_IncrementalTurnPersoWPersoW")] IncrementalTurnPersoWPersoW,
		[AI_Definition(SCR: "Action_IncrementalTurnPersoWPersoWPerso")] IncrementalTurnPersoWPersoWPerso,
		[AI_Definition(SCR: "Action_Camera_GoToPosition")] Camera_GoToPosition,
		[AI_Definition(SCR: "Action_Camera_GoToWP")] Camera_GoToWP,
		[AI_Definition(SCR: "Action_Camera_GoOverWay")] Camera_GoOverWay,
		[AI_Definition(SCR: "Action_Camera_GoOverWayBack")] Camera_GoOverWayBack,
		[AI_Definition(SCR: "Action_Camera_GoToNextWPOfWay")] Camera_GoToNextWPOfWay,
		[AI_Definition(SCR: "Action_Camera_GoToNextWPOfWayBack")] Camera_GoToNextWPOfWayBack,
		[AI_Definition(SCR: "Action_Camera_StayInWay")] Camera_StayInWay,
		[AI_Definition(SCR: "Action_Camera_GoToFromTarget")] Camera_GoToFromTarget,
		[AI_Definition(SCR: "Action_Camera_Shake")] Camera_Shake,
		[AI_Definition(SCR: "Action_Camera_WaitUntil")] Camera_WaitUntil,
		[AI_Definition(SCR: "Action_RotateModule")] RotateModule,
		[AI_Definition(SCR: "Action_RotateModuleToPerso")] RotateModuleToPerso,
		[AI_Definition(SCR: "Action_SwimToSurface")] SwimToSurface,
		[AI_Definition(SCR: "Action_WaitEndOfFade")] WaitEndOfFade,
		[AI_Definition(SCR: "Action_SendSoundRequestAndWait")] SendSoundRequestAndWait,
		[AI_Definition(SCR: "Action_SendVoiceRequestAndWait")] SendVoiceRequestAndWait,
		[AI_Definition(SCR: "Action_SendVoiceRequestPersoAndWait")] SendVoiceRequestPersoAndWait,
		[AI_Definition(SCR: "Action_GoToPosition2")] GoToPosition2,
		[AI_Definition(SCR: "Action_IncrementalTurnAbsDirection")] IncrementalTurnAbsDirection,
		[AI_Definition(SCR: "Action_IncTurnPersoAbsDirection")] IncTurnPersoAbsDirection,
		[AI_Definition(SCR: "Action_WaitNbFrames")] WaitNbFrames,
		#endregion
	}
}